alert("Se crea una ventana emergente")
console.log ("se agrega segunda version desde local")
console.log ("se agrega un cambio en ram pruebas")
console.log("neuvos cambios en rama pruebas")
console.log("Jaider rojas")
console.log ("2180685")
console.log ("Taller tec 2")